spring:
  datasource:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.98.113.109:8732/cheetah?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;useSSL=false
        username: root
        password: 123456
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        filters: stat,wall, slf4j
        filter:
          stat:
            db-type: mysql
            log-slow-sql: true
            merge-sql: true
            slow-sql-millis: 10000
          wall: 
            enabled: true
            db-type: mysql
            log-violation: true
            throw-exception: true
          slf4j:
            enabled: true
        web-stat-filter: 
          session-stat-enable: true
          session-stat-max-count: 20
          principal-session-name: sessionUser
          profile-enable: true
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff2,*.woff,*.ttf,*.svg,*.eot,/druid/*'
        stat-view-servlet: 
          reset-enable: false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  messages: 
    encoding: UTF-8
    cache-seconds: 3600
    basename: i18n/messages
  redis:
    host: 47.98.113.109
    port: 7001
    database: 0
    password: zylsite
    pool:
     maxActive: 5000 #最大连接数
     maxIdle: 30 #最大空闲连接数
     minIdle: 5 #最小空闲连接数
     maxWait: 3000  #获取连接最大等待时间 ms  #default -1
session:
  timeout: 60
logback:
  fileDir: E:/workspace/web/WorkSpace/logs/cheetah-web-backstage